language: php

php:
    - 7.3
    - 7.4

cache:
    directories:
        - $HOME/.composer/cache

env:
    global:
        - APPLICATION_ENV=development
        - APPLICATION_STORE=DE

install:
    - COMPOSER_MEMORY_LIMIT=-1 composer install --prefer-dist --no-interaction
    - if [[ $PREFER_LOWEST == 1 ]]; then COMPOSER_MEMORY_LIMIT=-1 composer update --prefer-lowest --prefer-stable --prefer-dist --no-interaction ; fi
    - if [[ $PREFER_LOWEST == 1 ]]; then COMPOSER_MEMORY_LIMIT=-1 composer require --dev dereuromark/composer-prefer-lowest; fi

script:
    - vendor/bin/phpcs src --standard=vendor/spryker/code-sniffer/Spryker/ruleset.xml
    - vendor/bin/codecept run --env isolated --coverage-xml

after_success:
    - vendor/bin/coveralls -vvv

notifications:
    email: false
